
name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Validate docker-compose.yml
        run: docker-compose -f docker-compose.yml config

      - name: Build Docker images
        run: docker-compose build

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 black pytest

      - name: Run flake8 linting
        run: flake8 .

      - name: Run black formatting check
        run: black . --check

      - name: Run tests
        run: pytest || echo "No tests found"

