name: Local CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  local-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo manually
        run: |
          git clone https://github.com/Umanagendra-M/AI-Partner.git repo
          cd repo
          ls -la

      - name: Set up Python manually
        run: |
          sudo apt install -y python3 python3-venv python3-pip
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f repo/requirements.txt ]; then pip install -r repo/requirements.txt; fi

      - name: Lint Python files
        run: |
          sudo apt install -y flake8
          flake8 repo --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Linting issues found"

      - name: Validate Docker Compose
        run: |
          cd repo
          docker-compose config

      - name: Build Docker Containers
        run: |
          cd repo
          docker-compose build
